const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const adminRole = await prisma.systemRole.create({
    data: {
      name: 'ADMIN',
      description: 'ADMIN role with Full permissions',
      permissions: {
        approver: true,
        createProduct: true,
        updateProduct: true,
        deleteProduct: true,
        viewProduct: true,
        createCategory: true,
        updateCategory: true,
        deleteCategory: true,
        viewCategory: true,
        createSupplier: true,
        updateSupplier: true,
        deleteSupplier: true,
        viewSupplier: true,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: true,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: true,
        viewInvoice: true,
        createEmployee: true,
        updateEmployee: true,
        deleteEmployee: true,
        viewEmployee: true,
        createTransaction: true,
        viewTransaction: true,
        createUser: true,
        updateUser: true,
        deleteUser: true,
        viewUser: true,
        createRole: true,
        updateRole: true,
        deleteRole: true,
        viewRole: true,
      },
    },
  });

  const internRole = await prisma.systemRole.create({
    data: {
      name: 'INTERN',
      description: 'Intern role with limited permissions',
      permissions: {
        approver: false,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: false,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: true,
        createCustomer: false,
        updateCustomer: false,
        deleteCustomer: true,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        createEmployee: false,
        updateEmployee: true,
        deleteEmployee: true,
        viewEmployee: true,
        createTransaction: false,
        viewTransaction: true,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: true,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: true,
      },
    },
  });

  const salesRepRole = await prisma.systemRole.create({
    data: {
      name: 'SALESREP',
      description: 'SalesRep role with limited permissions',
      permissions: {
        approver: false,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: false,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: true,
        createCustomer: false,
        updateCustomer: false,
        deleteCustomer: true,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        createEmployee: false,
        updateEmployee: true,
        deleteEmployee: true,
        viewEmployee: true,
        createTransaction: false,
        viewTransaction: true,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: true,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: true,
      },
    },
  });

  const cashier = await prisma.systemRole.create({
    data: {
      name: 'CASHIER',
      description: 'Cashier role with limited permissions',
      permissions: {
        approver: false,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: false,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: true,
        createCustomer: false,
        updateCustomer: false,
        deleteCustomer: true,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        createEmployee: false,
        updateEmployee: true,
        deleteEmployee: true,
        viewEmployee: true,
        createTransaction: false,
        viewTransaction: true,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: true,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: true,
      },
    },
  });

  const supervisor = await prisma.systemRole.create({
    data: {
      name: 'SUPERVISOR',
      description: 'Supervisor role with limited permissions',
      permissions: {
        approver: false,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: false,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: true,
        createCustomer: false,
        updateCustomer: false,
        deleteCustomer: true,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        createEmployee: false,
        updateEmployee: true,
        deleteEmployee: true,
        viewEmployee: true,
        createTransaction: false,
        viewTransaction: true,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: true,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: true,
      },
    },
  });

  const employee = await prisma.systemRole.create({
    data: {
      name: 'EMPLOYEE',
      description: 'Employee role with limited permissions',
      permissions: {
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: false,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: true,
        createCustomer: false,
        updateCustomer: false,
        deleteCustomer: true,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        createEmployee: false,
        updateEmployee: true,
        deleteEmployee: true,
        viewEmployee: true,
        createTransaction: false,
        viewTransaction: true,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: true,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: true,
      },
    },
  });

  console.log('Successfully seeded');
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
