# name: Deploy to DigitalOcean

# on:
#   push:
#     branches:
#       - development

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Deploy to DigitalOcean
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /home/projects/github/backend
#             git pull origin development
#             export NVM_DIR=~/.nvm
#             source ~/.nvm/nvm.sh
#             npm install
#             npm run build
#             echo "NEST APP BUILT SUCCESSFULLY"
#             cd /home/projects/live/noslag_backend
#             cp -Rf ../../github/backend/* ./
#             npm install
#             #pm2 start dist/main.js --name "noslag-backend"
#             pm2 restart noslag-backend
#             exit_status=$?
#             if [ $exit_status -ne 0 ]; then
#               echo "Error: Deployment failed. Stopping the app."
#               pm2 stop noslag-backend
#               pm2 logs noslag-backend --lines 10  # Display the last 10 lines of logs
#               exit $exit_status
#             else 
#               echo "PM2 service started"
#               exit $exit_status
#             fi
